# Generated by Django 4.2.10 on 2024-07-21 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_alter_photo_property'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
    ]
