# Generated by Django 4.2.10 on 2024-07-21 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_remove_user_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='url',
        ),
        migrations.AddField(
            model_name='photo',
            name='image',
            field=models.ImageField(default=1, upload_to='property_photos/'),
            preserve_default=False,
        ),
    ]
