# Generated by Django 4.2.10 on 2024-07-23 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_remove_photo_url_photo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='primary_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_photo_for_property', to='property.photo'),
        ),
    ]
